version: "3.8"
services:
  bot:
    build: .
    volumes:
      - .:/code
  db:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017